---
agent:
  id: "{{ inventory_hostname }}.stackable.demo"
  host: "{{ inventory_hostname }}.stackable.demo"

  parceldirectory: "/opt/distro/parcels"
  servicedirectory: "/etc/systemd/system"
  statedirectory: "/etc/distro/state"
  stateconfdir: "/etc/distro/config"
  logdirectory: "/tmp"

  binarydirectory: "/opt/distro/agent"
  binaryfile: "agent-0.1-SNAPSHOT-jar-with-dependencies.jar"


  configdirectory: "/etc/distro/agent"
  configfile: "agent.conf"

  version: "HEAD"


agentbinarylocation: "{{ agent.binarydirectory}}/{{ agent.binaryfile }}"
agentconfiglocation: "{{ agent.configdirectory }}/{{ agent.configfile }}"

filebeat_version: 7.8.0
filebeat_repo_version: "{{ filebeat_version.split('.')[0] }}.x"
filebeat_repo_baseurl: "https://artifacts.elastic.co/packages/{{ filebeat_repo_version }}/yum"

install_filebeat: yes
